apiVersion: v1
kind: Pod
metadata:
  name: sspod
  namespace: testing
spec:
  containers:
  - name: stupid-simple-container
    image: fedora
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      runAsUser: 0
